language: cpp
compiler: 
  - gcc 
  - clang
sudo: required
before_install:
  - sudo apt-get update
  - sudo apt-add-repository -y ppa:beineri/opt-qt562
  - sudo apt-get update
  - sudo apt-get install -y build-essential qt56-meta-minimal
  
install: true

script:
  source /opt/qt56/bin/qt56-env.sh && qmake && make
